# Generated by Django 3.0.1 on 2019-12-28 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentfile',
            name='description',
        ),
        migrations.RemoveField(
            model_name='imagefile',
            name='description',
        ),
        migrations.AddField(
            model_name='documentfile',
            name='informations',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='imagefile',
            name='informations',
            field=models.TextField(default=None, null=True),
        ),
    ]
