# Generated by Django 3.0.3 on 2020-03-24 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20191228_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='activities',
            field=models.ManyToManyField(blank=True, related_name='entities', to='core.Activity'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='addresses',
            field=models.ManyToManyField(blank=True, related_name='entities', through='core.EntityAddress', to='core.Address'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='phones',
            field=models.ManyToManyField(blank=True, related_name='entities', through='core.EntityPhone', to='core.Phone'),
        ),
    ]
