# Generated by Django 3.0.3 on 2020-03-24 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200324_2002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entityphone',
            name='phone_type',
        ),
        migrations.AddField(
            model_name='entityphone',
            name='type',
            field=models.IntegerField(choices=[(1, 'Mobile'), (2, 'Emergency'), (3, 'Home'), (4, 'Work')], default=1),
        ),
        migrations.DeleteModel(
            name='PhoneType',
        ),
    ]
