# Generated by Django 3.0.3 on 2020-03-24 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200324_2019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='activity_type',
        ),
        migrations.AddField(
            model_name='activity',
            name='type',
            field=models.IntegerField(choices=[(1, 'Unknown'), (2, 'Profession')], default=1),
        ),
        migrations.DeleteModel(
            name='ActivityType',
        ),
    ]
