# Generated by Django 3.0.8 on 2020-08-13 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20200813_0843'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documentfile',
            old_name='path_relative_to_media_root',
            new_name='is_path_relative',
        ),
        migrations.RenameField(
            model_name='imagefile',
            old_name='path_relative_to_media_root',
            new_name='is_path_relative',
        ),
    ]
