# Generated by Django 3.0.1 on 2019-12-23 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_pages', to='core.ImageFile')),
            ],
        ),
        migrations.CreateModel(
            name='BookParagraph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.BookPage')),
            ],
        ),
    ]
