# Generated by Django 3.0.3 on 2020-03-24 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20191228_1215'),
        ('app', '0002_bookpage_bookparagraph'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonTyped',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Person')),
                ('person_type', models.IntegerField(choices=[(1, 'Super administrator'), (2, 'Contributor')], default=2)),
            ],
            options={
                'ordering': ['date_v_start'],
                'abstract': False,
            },
            bases=('core.person',),
        ),
    ]
